### ISSUE TITLE
Support 4MB offset?

### ISSUE THREAD

**Issue by Onfy** [ArcheyChen/GBAMultiCartMenuV2#1]
Would it break anything to support roms on a Nx4MB offset? It looks like in findGames you could just change 8 to 4 so it would search by that offset... (haven't tried this yet.)

This would be helpful for 4MB roms, otherwise you waste half the space.

**Comment by ArcheyChen** [comment]
The reason I only supported 8MB a game is that the Flash needs to be erased in 256KB and written in 1 KB.

Like, we have a 2Gb(256MB) cart, if we split games in 8MB, we can have 32 games, one game needs one save slot, which will need 256KB. and 32 x 256KB = 8MB.

So, in my design, I leave the first 8MB to the menu, and the next 8MB to game saves. the rest of the space can be used to store the game.

If you change the game searching to every 4MB, well, you will have to :

1. use 16MB to save the save file.

2. or you can find a way to "merge" two saves into one 256KB block

3. or you might not support the games in 4MB offset to save

good luck hacking

**Comment by Onfy** [comment]
Insightful. I had been wondering how the saves are stored - but I assume this only applies if the cart has a battery? My cart is batteryless, and it seems to always store the saves in the games' banks. (Except a trick I found with the Game Boy Player.) Of course, with batteryless patches the games often need to be doubled in size anyway, so you still lose capacity that way.

I tried recompiling with it changed to 4, and it seems to work after a quick test.

(Anyway, I don't think I would make every game 4MB except to boast, rather I'd have a mix of different sizes.)

**Comment by ArcheyChen** [comment]
> Insightful. I had been wondering how the saves are stored - but I assume this only applies if the cart has a battery? My cart is batteryless, and it seems to always store the saves in the games' banks. (Except a trick I found with the Game Boy Player.) Of course, with batteryless patches the games often need to be doubled in size anyway, so you still lose capacity that way.
> 
> I tried recompiling with it changed to 4, and it seems to work after a quick test.
> 
> (Anyway, I don't think I would make every game 4MB except to boast, rather I'd have a mix of different sizes.)

Well, the problem will occur if you change it to 4MB when you place the game in 128MB+ space. because it will write to 16~24MB space, make sure there will be no game in it, otherwise it will over write the game.

About the battery problem, yes, my menu is designed to work with the battery(or you can replace the SRAM with fm28v100 FRAM, wich basically is a SRAM that not need battery)

When you go into the menu, it will copy the save from SRAM to Flash, and when you load a game, it will load the save from Flash to SRAM, that is how it works.

if you don't have a battery, and you use a baterless save patch, you can remove the backup save part. and move the meta data(which use to remember what is your last game) to the 8MB-256KB place.

then, you can use the 8MB~256MB for your game, can fell free to use 4MB games

**Comment by Onfy** [comment]
>Well, the problem will occur if you change it to 4MB when you place the game in 128MB+ space. because it will write to 16~24MB space, make sure there will be no game in it, otherwise it will over write the game.

This will affect any game after 128MB, regardless of how many there are or their sizes? I guess that would be good for a 128MB cart, at least...

>When you go into the menu, it will copy the save from SRAM to Flash, and when you load a game, it will load the save from Flash to SRAM, that is how it works.

I always choose no when it asks if I want to save (except when I made that work on GBP), I assume it doesn't write then?

Edit for anyone who finds this: it does. I assume it organizes this as soon as you load the menu, whether you save or not. The game at 16MB will be rendered unbootable, maybe your save will be lost. Fun!

>if you don't have a battery, and you use a baterless save patch, you can remove the backup save part. and move the meta data(which use to remember what is your last game) to the 8MB-256KB place.
> 
>then, you can use the 8MB~256MB for your game, can fell free to use 4MB games

I guess making a batteryless fork could be a fun project. Thanks!
